/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkplaceRouteImport } from './routes/workplace'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NavigatorRouteImport } from './routes/navigator'
import { Route as HealthRouteImport } from './routes/health'
import { Route as DestinationsRouteImport } from './routes/destinations'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const WorkplaceRoute = WorkplaceRouteImport.update({
  id: '/workplace',
  path: '/workplace',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NavigatorRoute = NavigatorRouteImport.update({
  id: '/navigator',
  path: '/navigator',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsRoute = DestinationsRouteImport.update({
  id: '/destinations',
  path: '/destinations',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/agent': typeof AgentRoute
  '/auth': typeof AuthRoute
  '/destinations': typeof DestinationsRoute
  '/health': typeof HealthRoute
  '/navigator': typeof NavigatorRoute
  '/profile': typeof ProfileRoute
  '/workplace': typeof WorkplaceRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/agent': typeof AgentRoute
  '/auth': typeof AuthRoute
  '/destinations': typeof DestinationsRoute
  '/health': typeof HealthRoute
  '/navigator': typeof NavigatorRoute
  '/profile': typeof ProfileRoute
  '/workplace': typeof WorkplaceRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/agent': typeof AgentRoute
  '/auth': typeof AuthRoute
  '/destinations': typeof DestinationsRoute
  '/health': typeof HealthRoute
  '/navigator': typeof NavigatorRoute
  '/profile': typeof ProfileRoute
  '/workplace': typeof WorkplaceRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/achievements'
    | '/agent'
    | '/auth'
    | '/destinations'
    | '/health'
    | '/navigator'
    | '/profile'
    | '/workplace'
    | '/api/chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/achievements'
    | '/agent'
    | '/auth'
    | '/destinations'
    | '/health'
    | '/navigator'
    | '/profile'
    | '/workplace'
    | '/api/chat'
  id:
    | '__root__'
    | '/'
    | '/achievements'
    | '/agent'
    | '/auth'
    | '/destinations'
    | '/health'
    | '/navigator'
    | '/profile'
    | '/workplace'
    | '/api/chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AchievementsRoute: typeof AchievementsRoute
  AgentRoute: typeof AgentRoute
  AuthRoute: typeof AuthRoute
  DestinationsRoute: typeof DestinationsRoute
  HealthRoute: typeof HealthRoute
  NavigatorRoute: typeof NavigatorRoute
  ProfileRoute: typeof ProfileRoute
  WorkplaceRoute: typeof WorkplaceRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workplace': {
      id: '/workplace'
      path: '/workplace'
      fullPath: '/workplace'
      preLoaderRoute: typeof WorkplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/navigator': {
      id: '/navigator'
      path: '/navigator'
      fullPath: '/navigator'
      preLoaderRoute: typeof NavigatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations': {
      id: '/destinations'
      path: '/destinations'
      fullPath: '/destinations'
      preLoaderRoute: typeof DestinationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AchievementsRoute: AchievementsRoute,
  AgentRoute: AgentRoute,
  AuthRoute: AuthRoute,
  DestinationsRoute: DestinationsRoute,
  HealthRoute: HealthRoute,
  NavigatorRoute: NavigatorRoute,
  ProfileRoute: ProfileRoute,
  WorkplaceRoute: WorkplaceRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
